### ISSUE TITLE
Scroll down in the bottomSheet does not work correctly

### ISSUE THREAD

**Issue by ilyasshafigin** [roudikk/guia#16]
Hi

I have a problem with the `bottomSheet`.
Screen record from guia sample app:

https://user-images.githubusercontent.com/7170090/218332852-123f3acd-4470-470a-989c-367805f4e4c5.mp4

Velocity of fling is not passed to children list.

I found the problem in [this](https://github.com/roudikk/guia/blob/master/guia/src/main/java/com/roudikk/guia/containers/BottomSheetLayout.kt#L223) method:

```kotlin
        override suspend fun onPreFling(available: Velocity): Velocity {
            val toFling = Offset(available.x, available.y).toFloat()
            return if (toFling < 0 && offset.value > Float.NEGATIVE_INFINITY) {
                performFling(velocity = toFling)
                // since we go to the anchor with tween settling, consume all for the best UX
                available
            } else {
                Velocity.Zero
            }
        }
```

If you replace it with this, it will work, but I don't know side effects:

```kotlin
        override suspend fun onPreFling(available: Velocity): Velocity {
            return Velocity.Zero
        }
```

https://user-images.githubusercontent.com/7170090/218334334-2e53a0b2-ce28-4662-980a-7295a4d1cb43.mp4

**Comment by roudikk** [comment]
Ah I think the problem could be that the original `ModalBottomSheetLayout` had the content inside a `Column`. I'll try first adding the Column back so the content can have a `ColumnScope` receiver. Or just perhaps remove the fling behaviour so the content can receive it

**Comment by roudikk** [comment]
I've applied your solution for now, can't see a side effect of setting that considering there is currently on `HalfExpanded` state.
